name: checkin_ou_client
description: Cliente Flutter multiplataforma offline-first para check-in universitário.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  connectivity_plus: ^6.0.5
  flutter_secure_storage: ^9.2.2
  drift: ^2.19.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  web: ^1.1.0
  drift_flutter: ^0.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.19.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
